/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ToDoItemService } from "../toDoItem.service";
import { ToDoItemCreateInput } from "./ToDoItemCreateInput";
import { ToDoItem } from "./ToDoItem";
import { ToDoItemFindManyArgs } from "./ToDoItemFindManyArgs";
import { ToDoItemWhereUniqueInput } from "./ToDoItemWhereUniqueInput";
import { ToDoItemUpdateInput } from "./ToDoItemUpdateInput";

export class ToDoItemControllerBase {
  constructor(protected readonly service: ToDoItemService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ToDoItem })
  async createToDoItem(
    @common.Body() data: ToDoItemCreateInput
  ): Promise<ToDoItem> {
    return await this.service.createToDoItem({
      data: data,
      select: {
        completed: true,
        createdAt: true,
        description: true,
        dueDate: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ToDoItem] })
  @ApiNestedQuery(ToDoItemFindManyArgs)
  async toDoItems(@common.Req() request: Request): Promise<ToDoItem[]> {
    const args = plainToClass(ToDoItemFindManyArgs, request.query);
    return this.service.toDoItems({
      ...args,
      select: {
        completed: true,
        createdAt: true,
        description: true,
        dueDate: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ToDoItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async toDoItem(
    @common.Param() params: ToDoItemWhereUniqueInput
  ): Promise<ToDoItem | null> {
    const result = await this.service.toDoItem({
      where: params,
      select: {
        completed: true,
        createdAt: true,
        description: true,
        dueDate: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ToDoItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateToDoItem(
    @common.Param() params: ToDoItemWhereUniqueInput,
    @common.Body() data: ToDoItemUpdateInput
  ): Promise<ToDoItem | null> {
    try {
      return await this.service.updateToDoItem({
        where: params,
        data: data,
        select: {
          completed: true,
          createdAt: true,
          description: true,
          dueDate: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ToDoItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteToDoItem(
    @common.Param() params: ToDoItemWhereUniqueInput
  ): Promise<ToDoItem | null> {
    try {
      return await this.service.deleteToDoItem({
        where: params,
        select: {
          completed: true,
          createdAt: true,
          description: true,
          dueDate: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
